{% set version = '0.0-8' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-combinat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/combinat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/combinat/combinat_{{ version }}.tar.gz
  sha256: 1513cf6b6ed74865bfdd9f8ca58feae12b62f38965d1a32c6130bef810ca30c1

build:
  number: 1007
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('combinat')"           # [not win]
    - "\"%R%\" -e \"library('combinat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=combinat
  license: GPL-2.0-only
  summary: routines for combinatorics
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
