appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: qP6nnuZLH/rwOfmVYSJxf2QMV6pC1elpvkRCzy5uScUc36gJj5qFDzQuK7pb286dHf5gaBfGzTvg3bt8EubpG4l5ThdipDkVNfy+iclLTaJV/azlg8r/68U9/GPWjiUtHXg/QYy+nW1UUASkNnxyO7cAxsF8QpdIl5IPQuMPSFB7pd3MsrRsh4KRkm6vxgfXU/rZa+gfTD+LlbVNbrFUGVq3xpDJBqZBwvFDtk9z8a6PP1sh+ZKvutZ4VziWGU60LjdCbO77Y0j8K6AXLGEs8XE9KPJv+q4jMIHaCZ+jmSFZtadkYZhYDQyoVruSYbNDxkyGgKS9NHFj0cU+x6PJBGqtx8BkfE8aiWggciv0oncLn+k1BOgaSIpyJOWZ4P9i2sHXgd+ORTwUk1aU8hI6Btl7D+t+jdXfVvm61Y5Q+e4An2mXmWmspbbIKfVXdCc4C68kmT+jCL21lrn26lWcUoW/oS55siV34nWL6AkniS7PIb1irr4MGRXdFitdtKSwnyE9NLQLXJnN0UFcsMREHaDU9CigZeDQ++k8eN8qR+t4Kquh56pA6/zcdjhYW/2QsgW1LoMED38MMFuN7PETtQGWxAdJl/+Zec8sEN8yBrfF3LAUuXByQl42e8HD1EIcqAQ/fkHe3J9YJ8lqQJQ4GRIa0P8h/DmmfBwV4/EqKGQ=
conda_forge_output_validation: true
