travis:
  secure:
    BINSTAR_TOKEN: ofwfdeKFs8jAXYnhtf1cThR8lW0tLCqcwtt8braVCS54g5rQ8zZOpfchTkMl+YotvHIRfSIFIS9mLrw9Qdgbu8zZqoH0lY2dkJK7zekMyq+VHEt7Ov9xfgjq90oadhVLtBD4XKpPmzlhA6MgMapdiyShV00gBVoeDQVL28Oc4ddbW8lErsAS848JuuP0NH229ouEp9TVMC+hD4NHq767gnnyiwtosC8UED05HGFtxZwQ7UyQSCRo6SxQZ0033yRyvlUhYlQ6slY1WDluY7PSYHqAhmyQUrVrc+b1ALCsxqoAVdrVW/qQNcjaD7PWkXexqzDpmqryrCxAhj0LGq+SLTGVCEYrwusQ+aC3s8HRcJMpqrAS4S5zLrEVt7hvPLHTle7DS1X9ykki/55iO3IGWc4e+slD86hq0wn4SQqt1XQcEUPoPR63/GL6/pPm3c+VxCBIwFOAQsIQl9nBfFQs/1ICMYk9rppNAGCuPu/OV4NJpGjInWLQlyYaePejff7/JqzuwGrwz/zqy2U+/z00c0jp2dGNG42oIAMJnyp5Rcj9aHZg3wZtV1xslQbtU6P5O7eMmgxx+BjRYen+w5BmXG0tGwK8ocY3l2DPS0QdiHLSzsqTVUPHd46YvtznGCu+gZhAlU3N+cnpy+zeGGQX8/DmC0voQ48bF5OXBwGPuE8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
